# Generated by Django 2.0.6 on 2018-12-02 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Indicators',
        ),
        migrations.AddField(
            model_name='on_off',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
